server:
  port: 7878

websocket:
  server:
    url: ws://${API_IP:localhost}:7777  # URL API "Обнаружителя"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://192.168.31.34:8761/eureka}
spring:
  application:
    name: NODE-SHTIL-FARVATER-${NUM:1}
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_URL:192.168.31.34:29092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false
  output:
    ansi:
      enabled: ALWAYS